### ISSUE TITLE
standard_init_linux.go:219 exec user process caused: exec format error

### ISSUE THREAD

**Issue by cooperspencer** [bitnami/minideb#99] opened 2021-02-18 13:08 UTC
Hi,

I tried to run bitnami/minideb:latest on my pi 4 raspbian and run into the following error while starting the container:
`standard_init_linux.go:219 exec user process caused: exec format error`
Is it possible that the go-binary wasn't compiled for the arm64?

**Comment by tcfw** [comment] 2021-02-18 23:41
I'm also getting this when minideb was used as based or init container.
Looking at docker hub, the different arch'd images are exactly the same size, which makes me think that the arm images are actually x86 (they should be _nearly_ the same size, but not **exactly** the same based on my experience of building arm images).

I tried out minideb:latest and even minideb:latest-arm64 on a m6g instance in AWS to run an apt install/update and it was downloading amd64 packages (also confirmed by `uname -m` as x86_64) - the only reason I managed to get the container image to run was most likely caused by having qemu-user-static package installed first.

**Comment by cooperspencer** [comment] 2021-02-19 06:43
I checked out the repository yesterday and the container on my pi and then it worked out fine.

**Comment by beltran-rubo** [comment] 2021-02-19 07:01
Thanks for reporting it! We just started working on adding multi-arch for Minideb this week and it seems an issue with Travis.org vs Travis.com account. Even the job uses Graviton it looks internally is an x86_64. 

We continue working on this and we estimate should be addressed next week. We will update this ticket when it was solved.

**Comment by beltran-rubo** [comment] 2021-02-22 14:46
@cooperspencer @tcfw this is now fixed, please reopen it if you find any issues.

**Closed by beltran-rubo** 2021-02-22 14:46 UTC
