### ISSUE TITLE
Cannot use sysctl in bitnami/minideb:latest for init container

### ISSUE THREAD

**Issue by yanngit** [bitnami/minideb#63] opened 2019-08-22 08:18 UTC
We are using the sysctlImage init container of [redis Helm chart](https://github.com/helm/charts/tree/master/stable/redis) to modify the kernel parameter somaxconn. With the latest version of minideb it seems like we cannot perform sysctl operations. We tried to do so with the minideb:stretch and it seems to be working. Is there any reason to that ? 
Thanks

PS : seems like the sysctl package has changed to procps, maybe it's related ...

**Comment by jonaseck2** [comment] 2019-08-30 07:56
It's the same for almost every single bitnami helm chart since they all use bitnami/minideb:latest as init containers for setting sysctl values.

Versioning this image and use specific versions in helm charts would avoid having a single point of failure that breaks most bitnami charts.

**Comment by james-w** [comment] 2019-08-30 10:34
Hi, thanks for the report everyone. We are looking in to fixing this.

**Comment by james-w** [comment] 2019-08-30 11:08
We are going to move away from using the `:latest` tag to avoid this happening again on the next Debian release.

For `sysctl` in particular it is provided by `procps` in both stretch and buster.

We will change the command for `elasticsearch`: https://github.com/bitnami/charts/commit/a76ffbb7b56a9e47ae65d8c898d6aa5364bc6c36

For redis the default doesn't use `sysctl`, so I believe you can edit your `values.yaml` to
install `procps` rather than `systemd` and it should work. We will update the docs for this.

**Comment by carrodher** [comment] 2019-08-31 07:04
Hi all, thanks for reporting this issue.

Bitnami uses the `bitnami/minideb` image to perform some basic actions as _initContainers_ in some charts, those ones that require it.
Mainly those actions are related to permissions and most _initContainers_ run a command like the following one
```
command: ["/bin/chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "{{ .Values.persistence.path }}"]
```
There are two cases (Redis and ElasticSearch) where the _initContainer_ perform `syctl` actions. The first one include in the _README_ how to configure the _initContainer_ to perform this action, while the second one directly include the command in the templates.

The issue, although it is not a good practice to use `latest` as tag anywhere, only affects Redis and ElasticSearch, not all the Bitnami charts because the other commands like `chown`, `mkdir`, etc are available without modifications across Debian versions.

We already sent different PRs fixing the issue, in those PRs we are doing two different changes:
- Replacing `latest` by `buster` as minideb tag in order to avoid major breaking changes in the future, but maintaining this tag updated on a daily basis.
- Installing `procps` as the first step in the _initContainer_ included in Redis and ElasticSearch to have `sysctl` working properly with the new Debian version.

You can find those PRs in the following links:
- 1 PR with all the changes in [bitnami/charts](https://github.com/bitnami/charts): https://github.com/bitnami/charts/pull/1384
- 7 PRs with the changes per chart in [helm/charts](https://github.com/helm/charts): https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Acarrodher+buster

**Comment by carrodher** [comment] 2019-09-19 09:10
I am closing this thread as it seems the issue is solved. Please do not hesitate to let us know if you think it is not. Feel free to add a comment here or create a new issue if needed.

**Closed by carrodher** 2019-09-19 09:10 UTC

**Comment by aneagoe** [comment] 2020-10-02 09:30
I've just hit this on an OKD 4.5 deployment. The init container logs below:
```
Reading package lists...
Building dependency tree...
The following additional packages will be installed:
  libncurses6 libprocps7
Recommended packages:
  libgpm2 psmisc
The following NEW packages will be installed:
  libncurses6 libprocps7 procps
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 423 kB of archives.
After this operation, 1213 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libncurses6 amd64 6.1+20181013-2+deb10u2 [102 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libprocps7 amd64 2:3.3.15-2 [61.7 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 procps amd64 2:3.3.15-2 [259 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 423 kB in 0s (5664 kB/s)
Selecting previously unselected package libncurses6:amd64.
(Reading database ... 6412 files and directories currently installed.)
Preparing to unpack .../libncurses6_6.1+20181013-2+deb10u2_amd64.deb ...
Unpacking libncurses6:amd64 (6.1+20181013-2+deb10u2) ...
Selecting previously unselected package libprocps7:amd64.
Preparing to unpack .../libprocps7_2%3a3.3.15-2_amd64.deb ...
Unpacking libprocps7:amd64 (2:3.3.15-2) ...
Selecting previously unselected package procps.
Preparing to unpack .../procps_2%3a3.3.15-2_amd64.deb ...
Unpacking procps (2:3.3.15-2) ...
Setting up libprocps7:amd64 (2:3.3.15-2) ...
Setting up libncurses6:amd64 (6.1+20181013-2+deb10u2) ...
Setting up procps (2:3.3.15-2) ...
update-alternatives: using /usr/bin/w.procps to provide /usr/bin/w (w) in auto mode
insserv: FATAL: service mountkernfs has to be enabled to use service procps
Processing triggers for libc-bin (2.28-10) ...
net.core.somaxconn = 16384
```
And init container specs:
```
Init Containers:
  init-sysctl:
    Container ID:  cri-o://52ead03268bd9e668e7fed92562568f47fbba1827ec11d9ed96a82aa7f4f80da
    Image:         docker.io/bitnami/minideb:buster
    Image ID:      docker.io/bitnami/minideb@sha256:96583ce2ba23fe8bfb82cef8dc7d1cfec84c2a0e9b77700123527cbd74f1a557
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      install_packages procps
      sysctl -w net.core.somaxconn=16384
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 02 Oct 2020 11:19:26 +0200
      Finished:     Fri, 02 Oct 2020 11:19:33 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host-sys from host-sys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-token-5bsx4 (ro)
```
Although the init container exists successfully, the value is *not* applied on the underlying host.

**Comment by carrodher** [comment] 2020-10-02 10:08
Please, take into account the `sysctl` command is applied to the kernel of the host machine. In this case the error
```
insserv: FATAL: service mountkernfs has to be enabled to use service procps
```
seems to be related to some configuration in the kernel itself, but it is not something the _initContainer_ can handle, in this case, the cluster administrator should solve the issue in the kernel. The _initContainer_ helps to set the default parameter when it is not properly set, but it was not created to handle another kind of situation.

If you are using the bitnami/redis Helm chart, you can customize the command used for the _initContainer_, as it is a privileged _initContainer_, you should be able to perform another kind of actions by customizing the `command`, see https://github.com/bitnami/charts/tree/master/bitnami/redis#host-kernel-settings
